- name: Add APT key
  become: true
  apt_key:
    url: 'https://pgp.mongodb.com/server-7.0.asc'
    state: present
  tags: install

- name: Add APT repository
  become: true
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-7.0.list'
    repo: 'deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse'
    state: present
    update_cache: yes
  tags: install

- name: Install mongodb package
  become: true
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  become: true
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
