---
- name: Install MondoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        url: 'https://pgp.mongodb.com/server-7.0.asc'
        state: present

    - name: Fetch the mongodb repo
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-7.0.list'
        repo: 'deb http://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/7.0 multiverse'
        state: present
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Unabled service
      systemd:
        name: mongod
        enabled: yes
        state: started
