---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: ubuntu/focal64
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
